name: Apply to become a maintainer
description: Interested in becoming a maintainer? Let us know!
title: "[Maintainer Application]: "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for your interest in becoming a maintainer!
        Please fill out the following form to apply to become a maintainer. A team member will review your application and get back to you as soon as possible.
        You may also send this application to [tristan.chin@chintristan.io](mailto:tristan.chin@chintristan.io).
  - type: checkboxes
    id: typescript
    attributes:
      label: TypeScript Experience
      description: By submitting this application, you assert that you are experienced with TypeScript.
      options:
        - label: I am experienced with TypeScript
          required: true
  - type: dropdown
    id: experience
    attributes:
      label: Other Experience
      description: Which one of these technologies are you comfortable with? Feel free to mention any other technologies you think are relevant in the next section!
      multiple: true
      options:
        - "OpenAI Node SDK"
        - "React"
        - "Angular"
        - "Vue"
        - "Ink"
        - "Electron"
        - "NestJS"
        - "Express"
        - "Discord.js"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Tell us about yourself
      description: Time to show off! Why should we choose you to become a maintainer?
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you?
      placeholder: Email address, Discord tag, etc.
    validations:
      required: true
