name: Publish

on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        options:
          - patch
          - minor
          - major
        description: "Release type"
        required: true

jobs:
  release-manual:
    name: Manual release
    if: github.ref_name == 'master' && github.event_name == 'workflow_dispatch' && inputs.type != ''
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Set Git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Release
        run: npm run release:${{ inputs.type }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
